### PR TITLE
Date fixes

### PR DESCRIPTION
**Pull request by hugovk**
# Before

image

image

It shows 1.11 is not yet dead, but it should.

---

JavaScript's `new Date` takes a `monthIndex`:

* Integer value representing the month, beginning with `0` for January to `11` for December.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

That means Django 1.11 is listed as EOL on 1 May, not today.

Rather than having to always remember to add dates like 1 May 2020 as `new Date(2020, 4, 1)`, this adds a wrapper to auto-adjust it for you.

image

---

Also, to update the colours, you need to manually adjust the data when the date changes:

```diff
    {
      taskID: "1.11",
      taskName: "Django 1.11 LTS",
-     resource: "security",
+     resource: "dead",
      start: date(2017, 04, 04),
      end: date(2020, 04, 01)
    },
```

This also adds some validation to automatically set past releases to dead and future ones to prerelease.

image

---

Also, there's currently no security releases on the chart, so comment out the yellow. It'd be better to be able to define resources with colours, but as it is, it auto-colours each resource group in order of the colours in the array.

image

### CODE REVIEW

**Comment by hugovk** [comment]
@di The `monthIndex` off-by-one affects https://python-release-cycle.glitch.me/script.js too.

**Comment by di** [comment]
@hugovk Thanks for the heads up. I just sent you an invitation to edit that glitch if you'd like to update it as well.

**Comment by hugovk** [comment]
@di Thanks, just updated it with https://github.com/jefftriplett/django-release-cycle/pull/4/commits/d44580867f09e7c79e222abd79f15d9c26de8ba8 and https://github.com/jefftriplett/django-release-cycle/pull/4/commits/31baecadc2e62f0ba4d2da7591fd6dd1ce6d9b71.

**Comment by jefftriplett** [comment]
@hugovk thank you for spotting it. I looked several times and could never spot it. 🎉

**Pull request merged**
