### PR TITLE
Add the vertical line to indicate current date

### PR DESCRIPTION
**Pull request by simkimsia**
I got work to do.. so I will come back to this PR later. I think the line went out of the original graph which is a tad ugly

I will create this PR that I intend to come back to fix.

Let me know ur thoughts on the twitter dialogue

cont'd from https://twitter.com/kimstacks/status/1235454481019494400?s=21

### CODE REVIEW

**Comment by simkimsia** [comment]
twitter_dd4ad06fafcdcda9950eaa7ead1acecf


Now the vertical line stops at the timeline


image
Also the container height is more flexibly adjusted rather than an arbitrary 600px. If you remove the releases prior to the 1.11, it will auto adjust

**Comment by simkimsia** [comment]
@jefftriplett let me know if u have further comments for me

**Comment by simkimsia** [comment]
so how? @jefftriplett

**Review by jefftriplett — APPROVED** [review]

**Comment by jefftriplett** [comment]
@simkimsia Thank you!

**Comment by simkimsia** [comment]
Welcome! @jefftriplett

**Pull request merged**
